# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Marek Hudyma's
subTitle:           Engineering Blog
author:             Marek Hudyma
description:
url:                'https://marekhudyma.com' # The base hostname & protocol for your site
github_username:    marekhudyma
linkedin_username:  marek-hudyma
email:              marek.hudyma@gmail.com
rss: rss

markdown:  kramdown
permalink: /:categories/:year/:month/:day/:title.html
sass:
  style: compressed

plugins:
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  marek:
    name:             Marek Hudyma
    bio:              My name is Marek Hudyma. I am a Backend Developer who loves coding and software architecture.
    gravatar:         '/assets/about/5b94db56.png'


############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
# see: https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md
# pagination:
#   enabled: true
#   debug: false
#   per_page: 12
#   sort_field: 'date'
#   sort_reverse: true